DATE = 'date'
NAME = 'name'
CLOSE_P = 'close_p'
RET = 'return'
VOLUME = 'volume'
SECTOR = 'sector'

CALIBRATE = 'calibrate'
VALIDATE = 'validate'

ENCODE_ACTIVATION = 'encode_activation'
DECODE_ACTIVATION = 'decode_activation'
OPTIMIZER = 'optimizer'
LOSS = 'loss'
SHUFFLE = 'shuffle'
EPOCH = 'epoch'
BATCH_SIZE = 'batch_size'
VALIDATION_SPLIT = 'validation_split'
ACTIVATION_I = 'activation_i'
ACTIVATION_O = 'activation_o'
